#!/usr/bin/env node
/**
 * Icon Update Script - D2-Guardian-Forge
 * 
 * This script processes icon updates from the web interface and creates a PR
 * Usage: node scripts/update-icons.js <changes-file>
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.join(__dirname, '..');

/**
 * Process icon changes and create a PR
 */
async function processIconChanges(changesFilePath) {
  console.log('📦 Processing icon changes...');
  
  // Read changes file
  const changesData = JSON.parse(fs.readFileSync(changesFilePath, 'utf8'));
  const { changes, files } = changesData;
  
  if (!changes || changes.length === 0) {
    console.error('❌ No changes found in the changes file');
    process.exit(1);
  }
  
  console.log(`✅ Found ${changes.length} icon change(s)`);
  
  // Create a new branch
  const branchName = `icon-update-${Date.now()}`;
  console.log(`🌿 Creating branch: ${branchName}`);
  
  try {
    await execAsync(`git checkout -b ${branchName}`);
  } catch (error) {
    console.error('❌ Failed to create branch:', error.message);
    process.exit(1);
  }
  
  // Process each icon change
  const processedChanges = [];
  
  for (let i = 0; i < changes.length; i++) {
    const change = changes[i];
    const { category, name, fileName } = change;
    const fileKey = `file_${i}`;
    
    if (!files[fileKey]) {
      console.warn(`⚠️  File not found for ${name}, skipping`);
      continue;
    }
    
    const targetPath = path.join(ROOT_DIR, 'public', 'icons', category, fileName);
    const fileData = Buffer.from(files[fileKey], 'base64');
    
    console.log(`📝 Updating: ${category}/${name}`);
    
    // Backup old file
    const backupPath = `${targetPath}.backup`;
    if (fs.existsSync(targetPath)) {
      fs.copyFileSync(targetPath, backupPath);
    }
    
    // Write new file
    fs.writeFileSync(targetPath, fileData);
    
    processedChanges.push({
      category,
      name,
      path: `public/icons/${category}/${fileName}`,
      oldPath: backupPath
    });
  }
  
  console.log(`✅ Processed ${processedChanges.length} icon(s)`);
  
  // Stage changes
  console.log('📦 Staging changes...');
  await execAsync('git add public/icons/');
  
  // Create commit
  const commitMessage = `Update ${processedChanges.length} icon(s)\n\n${processedChanges.map(c => `- ${c.category}/${c.name}`).join('\n')}`;
  console.log('💾 Creating commit...');
  await execAsync(`git commit -m "${commitMessage}"`);
  
  // Push branch
  console.log('🚀 Pushing branch...');
  await execAsync(`git push origin ${branchName}`);
  
  // Generate PR body
  const prBody = generatePRBody(processedChanges);
  
  console.log('\n✅ Icon changes committed and pushed!');
  console.log(`\n📋 Next steps:`);
  console.log(`1. Go to GitHub: https://github.com/partybrasil/D2-Guardian-Forge/compare/${branchName}`);
  console.log(`2. Create a Pull Request with the following body:\n`);
  console.log(prBody);
  
  // Clean up backup files
  processedChanges.forEach(change => {
    if (fs.existsSync(change.oldPath)) {
      fs.unlinkSync(change.oldPath);
    }
  });
}

/**
 * Generate PR body with before/after comparison
 */
function generatePRBody(changes) {
  let body = `# Icon Updates\n\n`;
  body += `This PR updates ${changes.length} icon(s) from the Icon Editor.\n\n`;
  body += `## Changed Icons\n\n`;
  
  changes.forEach(change => {
    body += `### ${change.name} (${change.category})\n\n`;
    body += `- **Path**: \`${change.path}\`\n`;
    body += `- **Old Icon**: ![Old](${change.oldPath})\n`;
    body += `- **New Icon**: ![New](${change.path})\n\n`;
  });
  
  body += `\n---\n\n`;
  body += `Generated by Icon Editor | [View Documentation](docs/ICON_SYSTEM.md)`;
  
  return body;
}

// Main execution
const args = process.argv.slice(2);
if (args.length === 0) {
  console.error('Usage: node scripts/update-icons.js <changes-file>');
  process.exit(1);
}

processIconChanges(args[0]).catch(error => {
  console.error('❌ Error processing icon changes:', error);
  process.exit(1);
});
